### ISSUE TITLE
Incorrect additions in plus method

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#1]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 17:45 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/1_

----

The Calculator.plus method is producing incorrect results.

**Comment by jonesst** [comment]
claimed
