### ISSUE TITLE
The volume of a cube is not correct

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#10]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 18:20 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/10_

----

The volume of a cube returned from the Calculator.cubeVol method is incorrect.

**Comment by addv12345** [comment]
Claimed
