### ISSUE TITLE
Change plus to add

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#12]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 18:57 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/12_

----

For naming consistency change the name of the plus method to be add.

**Comment by ewurabena** [comment]
I can help!
