### ISSUE TITLE
Chang hypot to hypotenuse

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#16]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 19:00 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/16_

----

Rename the hypot method to hypotenuse to enhance readability.

**Comment by stuartComp132** [comment]
call this one

**Comment by icatat** [comment]
Briona and I can also contribute to this one
