### ISSUE TITLE
Rename cirPer

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#20]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 19:03 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/20_

----

Rename the cirPer method to circlePerimeter to improve code readability.

**Comment by chaomt** [comment]
Connor and I want to fix this!
