### ISSUE TITLE
Areas of circles are incorrect

### ISSUE THREAD

**Issue by braughtg** [COMP491/github-issues-activity#8]
<a href="https://github.com/braughtg"><img src="https://avatars3.githubusercontent.com/u/16962482?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [braughtg](https://github.com/braughtg)**
_Sunday Sep 09, 2018 at 18:19 GMT_
_Originally opened as https://github.com/braughtg/github-issues-activity-f18/issues/8_

----

The area of a circle of radius r as computed by the Calculator.cirAr method is incorrect.

**Comment by chaomt** [comment]
Connor and I want to fix this bug.
